name: Quarkus CI

on: [push]

jobs:
  build:
    name: Quarkus - Getting Started
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          cd quarkus-getting-started
          chmod +x gradlew
          ./gradlew assemble test
